<a href="https://colab.research.google.com/github/gmadhuri10/colab-python-tasks/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np

# Create random vector of size 15 with integers from 1 to 20
arr = np.random.randint(1, 21, size=15)
print("Original array:\n", arr)

# Reshape the array to 3x5
reshaped_arr = arr.reshape(3, 5)
print("\nReshaped array (3x5):\n", reshaped_arr)

# Print array shape
print("\nArray shape:", reshaped_arr.shape)

# Replace the max in each row by 0
for i in range(reshaped_arr.shape[0]):
    max_index = reshaped_arr[i].argmax()
    reshaped_arr[i][max_index] = 0

print("\nModified array (max in each row replaced by 0):\n", reshaped_arr)


Original array:
 [ 8 17 18  9 16  7  6  4  4 15 16  9  4 13 19]

Reshaped array (3x5):
 [[ 8 17 18  9 16]
 [ 7  6  4  4 15]
 [16  9  4 13 19]]

Array shape: (3, 5)

Modified array (max in each row replaced by 0):
 [[ 8 17  0  9 16]
 [ 7  6  4  4  0]
 [16  9  4 13  0]]


In [3]:
import numpy as np

# Create a 4x3 array with 4-byte integer elements (int32)
arr = np.arange(1, 13, dtype=np.int32).reshape(4, 3)

# Print the array
print("Array:\n", arr)

# Print shape
print("\nShape of the array:", arr.shape)

# Print type
print("Type of the array:", type(arr))

# Print data type
print("Data type of the elements:", arr.dtype)



Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the elements: int32


In [4]:
import numpy as np

# Define the square matrix
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Display results
print("Eigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors (columns):\n", eigenvectors)


Eigenvalues:
 [2. 1.]

Right Eigenvectors (columns):
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [5]:
import numpy as np

# Define the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Compute sum of diagonal elements
diag_sum = np.trace(arr)

print("Sum of diagonal elements:", diag_sum)


Sum of diagonal elements: 4


In [7]:
import numpy as np

# Original 3x2 array
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print("Original array (3x2):\n", arr)

# Reshape to 2x3
reshaped_arr = arr.reshape(2, 3)

print("\nReshaped array (2x3):\n", reshaped_arr)


Original array (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
 [[1 2 3]
 [4 5 6]]
